name: C/C++ CI

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: Compile server.c
      run: gcc server.c -o server
    - name: Compile client.c
      run: gcc client.c -o client