name: C/C++ CI

on:
    push:
        branches: [ "dev" ]
    pull_request:
        branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: Compile server.cpp
      run: g++ server.cpp -o server
    - name: Compile client.cpp
      run: g++ client.cpp -o client
